apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: project03-replicaset
  labels:
    app: project03-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: project03-rs
  template:
    metadata:
      labels:
        app: project03-rs
    spec:
      containers:
        - name: project03-replicaset
          image: vijay9440/project034:0.1.0
          ports:
            - containerPort: 80
